# 单图 DBLP：从 data/DBLP_four_area_processed/nodes.jsonl + edges.jsonl 加载一张图
name: 'dblp_single'
datadir: 'data/DBLP_four_area_processed'
remove_h: null
molecules: False
spectre: False
pin_memory: False
directed: True
diffuse: 'subtype'
heterogeneous: True
