name: 'hghg_subgraphs'
datadir: 'data/HGHG_subgraphs'
remove_h: null
molecules: False
spectre: False
pin_memory: False
directed: True
diffuse: 'subtype'
heterogeneous: True

# Optional single-graph mode
single_graph: False
single_graph_split: 'train'
single_graph_index: 0
