name: 'pubmed_subgraphs'
datadir: 'data/PubMed_subgraphs'
remove_h: null
molecules: False
spectre: False
pin_memory: False
directed: True
diffuse: 'subtype'
heterogeneous: True
single_graph: False
single_graph_split: 'train'
single_graph_index: 0
